version: '3.8'
services:
  millenial-pg:
    image: postgres:13
    container_name: millenial-pg
    restart: always
    environment:
      POSTGRES_DB: millenialdb
      POSTGRES_USER: usermillenial
      POSTGRES_PASSWORD: secret1234
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql